/*
© Cutter Systems spol. s r.o., 2018
Author: Petr Kalandra (kalandra@cutter.cz)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
<http://www.apache.org/licenses/LICENSE-2.0>.
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

using Newtonsoft.Json;
using System.Collections.Generic;
using RosSharp.RosBridgeClient.Messages.Standard;

namespace RosSharp.RosBridgeClient.Messages.MoveIt
{
	public class MoveGroupResult
	{
		[JsonIgnore]
		public const string RosMessageName = "moveit_msgs/MoveGroupResult";

		// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
		// An error code reflecting what went wrong
		public MoveItErrorCodes error_code;

		// The full starting state of the robot at the start of the trajectory
		public RobotState trajectory_start;

		// The trajectory that moved group produced for execution
		public RobotTrajectory planned_trajectory;

		// The trace of the trajectory recorded during execution
		public RobotTrajectory executed_trajectory;

		// The amount of time it took to complete the motion plan
		public double planning_time;


		public MoveGroupResult()
		{
			error_code = new MoveItErrorCodes();
			trajectory_start = new RobotState();
			planned_trajectory = new RobotTrajectory();
			executed_trajectory = new RobotTrajectory();
		}
	}
}
