/*
© Cutter Systems spol. s r.o., 2018
Author: Petr Kalandra (kalandra@cutter.cz)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
<http://www.apache.org/licenses/LICENSE-2.0>.
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

using Newtonsoft.Json;
using System.Collections.Generic;
using RosSharp.RosBridgeClient.Messages.Standard;

namespace RosSharp.RosBridgeClient.Messages.Control
{
	public class FollowJointTrajectoryGoal
	{
		[JsonIgnore]
		public const string RosMessageName = "control_msgs/FollowJointTrajectoryGoal";

		// ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
		// The joint trajectory to follow
		public RosSharp.RosBridgeClient.Messages.Trajectory.JointTrajectory trajectory;

		// Tolerances for the trajectory.  If the measured joint values fall
		// outside the tolerances the trajectory goal is aborted.  Any
		// tolerances that are not specified (by being omitted or set to 0) are
		// set to the defaults for the action server (often taken from the
		// parameter server).
		// Tolerances applied to the joints as the trajectory is executed.  If
		// violated, the goal aborts with error_code set to
		// PATH_TOLERANCE_VIOLATED.
		public List<JointTolerance> path_tolerance;

		// To report success, the joints must be within goal_tolerance of the
		// final trajectory value.  The goal must be achieved by time the
		// trajectory ends plus goal_time_tolerance.  (goal_time_tolerance
		// allows some leeway in time, so that the trajectory goal can still
		// succeed even if the joints reach the goal some time after the
		// precise end time of the trajectory).
		//
		// If the joints are not within goal_tolerance after "trajectory finish
		// time" + goal_time_tolerance, the goal aborts with error_code set to
		// GOAL_TOLERANCE_VIOLATED
		public List<JointTolerance> goal_tolerance;

		public Duration goal_time_tolerance;


		public FollowJointTrajectoryGoal()
		{
			trajectory = new RosSharp.RosBridgeClient.Messages.Trajectory.JointTrajectory();
			path_tolerance = new List<JointTolerance>();
			goal_tolerance = new List<JointTolerance>();
			goal_time_tolerance = new Duration();
		}
	}
}
